[2023-11-15T17:44:41.694+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:41.741+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:42.294+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:42.306+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:43.189+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T17:44:43.335+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-03T00:00:00+00:00 [queued]>
[2023-11-15T17:44:43.340+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 6
[2023-11-15T17:44:43.514+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task1> on 2023-11-03 00:00:00+00:00
[2023-11-15T17:44:43.575+0000] {standard_task_runner.py:57} INFO - Started process 77 to run task
[2023-11-15T17:44:43.697+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task1', 'scheduled__2023-11-03T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmpjroqtmuq']
[2023-11-15T17:44:43.744+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask task1
[2023-11-15T17:44:44.364+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:44.367+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-03T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:44.399+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task1 scheduled__2023-11-03T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:44:45.692+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T00:00:00+00:00'
[2023-11-15T17:44:45.767+0000] {logging_mixin.py:151} INFO - Error al conectar a la base de datos: invalid literal for int() with base 10: 'None'
[2023-11-15T17:44:45.769+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:44:45.797+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task1, execution_date=20231103T000000, start_date=20231115T174443, end_date=20231115T174445
[2023-11-15T17:44:46.155+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:44:46.464+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
