[2023-11-15T17:45:05.272+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:45:05.293+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1'
[2023-11-15T17:45:05.463+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:45:05.479+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1'
[2023-11-15T17:45:05.950+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T17:45:06.109+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-09T00:00:00+00:00 [queued]>
[2023-11-15T17:45:06.113+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 6
[2023-11-15T17:45:06.547+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task1> on 2023-11-09 00:00:00+00:00
[2023-11-15T17:45:06.616+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2023-11-15T17:45:06.752+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task1', 'scheduled__2023-11-09T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmpheq5ul5e']
[2023-11-15T17:45:06.801+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask task1
[2023-11-15T17:45:07.608+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:45:07.621+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-09T00:00:00+00:00/task_id=task1'
[2023-11-15T17:45:07.643+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task1 scheduled__2023-11-09T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:45:09.239+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-09T00:00:00+00:00'
[2023-11-15T17:45:09.255+0000] {logging_mixin.py:151} INFO - Error al conectar a la base de datos: invalid literal for int() with base 10: 'None'
[2023-11-15T17:45:09.259+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:45:09.408+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task1, execution_date=20231109T000000, start_date=20231115T174505, end_date=20231115T174509
[2023-11-15T17:45:09.607+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:45:09.826+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
