[2023-11-15T17:44:45.894+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:45.981+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:46.485+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:46.501+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:47.555+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T17:44:47.693+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: peliculas_dag.task1 scheduled__2023-11-06T00:00:00+00:00 [queued]>
[2023-11-15T17:44:47.710+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 6
[2023-11-15T17:44:48.061+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task1> on 2023-11-06 00:00:00+00:00
[2023-11-15T17:44:48.147+0000] {standard_task_runner.py:57} INFO - Started process 80 to run task
[2023-11-15T17:44:48.213+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'peliculas_dag', 'task1', 'scheduled__2023-11-06T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/peliculas_dag.py', '--cfg-path', '/tmp/tmp06rphrp3']
[2023-11-15T17:44:48.269+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask task1
[2023-11-15T17:44:49.082+0000] {logging_mixin.py:151} INFO - Changing /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509
[2023-11-15T17:44:49.097+0000] {logging_mixin.py:151} INFO - Failed to change /opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=peliculas_dag/run_id=scheduled__2023-11-06T00:00:00+00:00/task_id=task1'
[2023-11-15T17:44:49.196+0000] {task_command.py:415} INFO - Running <TaskInstance: peliculas_dag.task1 scheduled__2023-11-06T00:00:00+00:00 [running]> on host 566b22168472
[2023-11-15T17:44:50.544+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='cristian' AIRFLOW_CTX_DAG_ID='peliculas_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-06T00:00:00+00:00'
[2023-11-15T17:44:50.711+0000] {logging_mixin.py:151} INFO - Error al conectar a la base de datos: invalid literal for int() with base 10: 'None'
[2023-11-15T17:44:50.752+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T17:44:50.994+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=peliculas_dag, task_id=task1, execution_date=20231106T000000, start_date=20231115T174447, end_date=20231115T174450
[2023-11-15T17:44:51.759+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T17:44:52.402+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
